version: '3'
services:
    ####################################################################################################
    # Redis
    ####################################################################################################
    redis:
        container_name: Scraper_Redis
        image: redis:latest
        ports:
            - "6379:6379"
        expose:
            - 6379
        volumes:
            - redisData:/data
    ####################################################################################################
    # MySQL
    ####################################################################################################
    mysql:
        container_name: Scraper_MySQL
        image: mysql:5.7
        ports:
           - "3306:3306"
        expose:
           - 3306
        volumes:
           - mysqlData:/var/lib/mysql/
        environment:
           MYSQL_ROOT_PASSWORD: root
           MYSQL_USER: scraper
           MYSQL_PASSWORD: root
           MYSQL_DATABASE: scraper
    ####################################################################################################
    # Phpmyadmin
    ####################################################################################################
    phpmyadmin:
        container_name: Scraper_PhpMyAdmin
        image: phpmyadmin/phpmyadmin:latest
        environment:
           - PMA_HOST=mysql
           - PMA_PORT=3306
           - PMA_USER=scraper
           - PMA_PASSWORD=root
        ports:
           - '8081:80'
        links:
           - mysql
volumes:
  mysqlData:
  redisData: